ALTER TABLE posts
    ADD COLUMN is_travel_post TINYINT(1) DEFAULT NULL,
    ADD COLUMN region_raw VARCHAR(255) DEFAULT NULL,
    ADD COLUMN region VARCHAR(64) DEFAULT NULL,
    ADD COLUMN mentioned_month TINYINT UNSIGNED DEFAULT NULL,
    ADD COLUMN mentioned_day TINYINT UNSIGNED DEFAULT NULL,
    ADD COLUMN extraction_version TINYINT UNSIGNED DEFAULT NULL,
    ADD INDEX (region);
